[package]
name = "github"
version = "0.1.0"
authors = ["Kyle Clemens <me@kyleclemens.com>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"
hyper = "0.9"

[dev-dependencies]
dotenv = "0.8"
